version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: typescript
      POSTGRES_PASSWORD: tsapp
      POSTGRES_DB: dockerts
    networks:
        - backend

  app:
    build: .
    ports:
    - "5000:5000"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: typescript
      POSTGRES_PASSWORD: tsapp
      POSTGRES_DBNAME: dockerts
      REACT_APP_API_URL: "http://example.com:5000/"
    networks:
      - backend
    depends_on:
      - db
networks:
  backend:
    driver: "bridge"
volumes:
  database_data:
